# -*- coding: utf-8 -*-
"""EBAC - CALCULADORA PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Inh2WlOWmESJLoZtBSZyURuEym-u-7tB

# Código da calculadora inteligente PYTHON

***Esta calculadora vai fazer os seguintes calculos:***
*   fazer os calculos padrões
*   Calcular raiz quadrada
*   Calcular o resto da divisão
*
"""

import math

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
num1_tipo = type(num1)
num2_tipo = type(num2)
print("O tipo do primeiro número é: ", num1_tipo)
print("O tipo do segundo número é: ", num2_tipo)
print("Escolha a operação que deseja realizar:")
print("1. Adição")
print("2. Subtração")
print("3. Multiplicação")
print("4. Divisão")
print("5. Resto da Divisão")
print("6. Raiz Quadrada")
operacao = int(input("Digite o número da operação desejada: "))
if operacao == 1:
      resultado = num1 + num2
      print("O resultado da adição é: ", resultado)

elif operacao == 2:
          resultado = num1 - num2
          print("O resultado da subtração é: ", resultado)

elif operacao == 3:
            resultado = num1 * num2
            print("O resultado da multiplicação é: ", resultado)

elif operacao == 4:
              resultado = num1 / num2
              print("O resultado da divisão é: ", resultado)

elif operacao == 5:
              resultado = num1 % num2
              print("O resto da divisão é: ", resultado)

              #Usando a função da raiz quadrada sqrt()
elif operacao == 6:
    resultado = math.sqrt(num1)
    print("A raiz quadrada do número é: ", resultado)
    print("OK, Até a próxima!!!")
elif True: # Added a condition to the elif statement
    print("Você não pode inserir caracteres na calculadora, apenas numeros!")